name: Sync with upstream

on:
  schedule:
    - cron: '0 2 * * *'   # every day at 2 AM UTC
  workflow_dispatch:       # manual trigger enabled

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/lyfe00011/levanter.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Reset main branch to upstream/main
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Push changes to origin main branch
        run: git push origin main --force
